apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
data:
  alerts.yml: |
    groups:
    - name: flask-app-slos
      rules:
      - alert: HighErrorRate
        expr: rate(app_request_count_total[5m]) == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Flask app is receiving no traffic"
          description: "No requests in the last 5 minutes - possible outage"

      - alert: PodNotReady
        expr: kube_pod_status_ready{condition="true"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Pod is not ready"
          description: "A pod has been not ready for more than 1 minute"
