name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t prasad-flask-app ./flask-app

    - name: Run tests
      run: |
        docker run -d -p 5000:5000 prasad-flask-app
        sleep 3
        curl http://localhost:5000/health
